require('dotenv').config();
const { pool, query } = require('../config/db');

const ALTERS = [
  `ALTER TABLE Usuarios ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Usuarios ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Usuarios ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Fiadores ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Fiadores ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Fiadores ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Garantias ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Garantias ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Garantias ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS cuota_semanal_base DECIMAL(12,2) DEFAULT 0`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS frecuencia_semana INT DEFAULT 1`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS dias_de_cobro JSON DEFAULT NULL`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS periodicidad VARCHAR(20) DEFAULT 'SEMANAL'`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS renovacion_previa_id VARCHAR(36) DEFAULT NULL`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Prestamos ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Pagos ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Pagos ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Pagos ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Gestiones_No_Pago ADD COLUMN IF NOT EXISTS is_synced TINYINT(1) DEFAULT 0`,
  `ALTER TABLE Gestiones_No_Pago ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`,
  `ALTER TABLE Gestiones_No_Pago ADD COLUMN IF NOT EXISTS deleted_at DATETIME DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS primer_nombre VARCHAR(80) DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS segundo_nombre VARCHAR(80) DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS primer_apellido VARCHAR(80) DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS segundo_apellido VARCHAR(80) DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS actividad_economica VARCHAR(150) DEFAULT NULL`,
  `ALTER TABLE Clientes ADD COLUMN IF NOT EXISTS cobrador_id VARCHAR(36) DEFAULT NULL`,
  `ALTER TABLE Fiadores MODIFY COLUMN cedula VARCHAR(40) NOT NULL`,
];

async function fix() {
  for (const sql of ALTERS) {
    try {
      await query(sql);
      console.log('OK:', sql.slice(0, 72));
    } catch (e) {
      console.log('Skip:', e.message);
    }
  }
  console.log('\n✔ Esquema alineado con la app (columnas sync/offline).');
  await pool.end();
}

fix().catch((err) => {
  console.error('❌ Error fix-schema:', err.message);
  process.exit(1);
});
